# Generated by Django 5.2.7 on 2025-10-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='WhyChoose',
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(default='Explore Courses', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(upload_to='hero_images/'),
        ),
    ]
