# Generated by Django 5.2.7 on 2025-10-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_delete_aboutsection_delete_course_delete_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('nav_home', models.CharField(default='Home', max_length=50)),
                ('nav_about', models.CharField(default='About us', max_length=50)),
                ('nav_courses', models.CharField(default='Courses', max_length=50)),
                ('nav_gallery', models.CharField(default='Gallery', max_length=50)),
                ('nav_contact', models.CharField(default='Contact us', max_length=50)),
                ('nav_login', models.CharField(default='Login', max_length=50)),
                ('heading', models.CharField(max_length=200)),
                ('sub_heading', models.TextField()),
                ('button_text', models.CharField(default='Explore Courses', max_length=50)),
                ('hero_image', models.ImageField(upload_to='home/')),
            ],
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
