# Generated by Django 5.2.7 on 2025-10-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_homepage_delete_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About LingoSeed', max_length=200)),
                ('description1', models.TextField()),
                ('description2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='about_images/')),
                ('trainer_text', models.CharField(default='Qualified Trainers', max_length=100)),
                ('skill_text', models.CharField(default='Skill-Based Learning', max_length=100)),
                ('global_text', models.CharField(default='Global Communication Focus', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(default='logos/default.png', upload_to='logos/'),
        ),
    ]
