# Generated by Django 5.2.7 on 2025-10-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_aboutsection_alter_homepage_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('bg_color', models.CharField(default='#2e5831', max_length=50)),
                ('text_color', models.CharField(default='#ffffff', max_length=50)),
                ('button_bg', models.CharField(default='#faebd7', max_length=50)),
                ('button_text_color', models.CharField(default='#000000', max_length=50)),
            ],
        ),
    ]
