# Generated by Django 5.2.7 on 2025-10-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_whychoose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('feedback', models.TextField()),
                ('stars', models.IntegerField(default=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
        ),
    ]
