# Generated by Django 5.2.7 on 2025-10-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='feedback',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='role',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default=1, upload_to='testimonials/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
