# Generated by Django 5.2.7 on 2025-10-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_rename_feedback_testimonial_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer/')),
                ('academy_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200)),
                ('copyright_text', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=200)),
                ('link_home', models.CharField(default='Home', max_length=100)),
                ('link_about', models.CharField(default='About', max_length=100)),
                ('link_courses', models.CharField(default='Courses', max_length=100)),
                ('link_contact', models.CharField(default='Contact', max_length=100)),
                ('course1', models.CharField(max_length=150)),
                ('course2', models.CharField(max_length=150)),
                ('course3', models.CharField(max_length=150)),
                ('course4', models.CharField(max_length=150)),
                ('course5', models.CharField(max_length=150)),
                ('course6', models.CharField(max_length=150)),
            ],
        ),
    ]
