# Generated by Django 5.2.7 on 2025-10-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_footerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinfo',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='instagram',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='link_about',
            field=models.CharField(default='About', max_length=50),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='link_contact',
            field=models.CharField(default='Contact', max_length=50),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='link_courses',
            field=models.CharField(default='Courses', max_length=50),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='link_home',
            field=models.CharField(default='Home', max_length=50),
        ),
    ]
