# Generated by Django 5.2.7 on 2025-10-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_alter_footerinfo_email_alter_footerinfo_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='footer/')),
                ('site_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=255)),
                ('link_home', models.CharField(default='Home', max_length=100)),
                ('link_about', models.CharField(default='About', max_length=100)),
                ('link_courses', models.CharField(default='Courses', max_length=100)),
                ('link_contact', models.CharField(default='Contact', max_length=100)),
                ('courses', models.TextField(help_text='Enter one course per line')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=100)),
                ('copyright_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='FooterInfo',
        ),
    ]
