# Generated by Django 5.2.7 on 2025-10-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_footer_delete_footerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='footer/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('instagram', models.CharField(max_length=255)),
                ('year', models.CharField(default='2025', max_length=4)),
                ('courses_list', models.ManyToManyField(blank=True, to='edu.coursename')),
            ],
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
