# Generated by Django 5.2.7 on 2025-10-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_coursename_footerinfo_delete_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinfo',
            name='courses_list',
            field=models.ManyToManyField(to='edu.program'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='instagram',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='institute_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='tagline',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='year',
            field=models.CharField(default='2025', max_length=10),
        ),
    ]
