# Generated by Django 5.2.7 on 2025-10-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_alter_footerinfo_courses_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerinfo',
            name='courses_list',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='institute_name',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='year',
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='about',
            field=models.CharField(default='About', max_length=100),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='brand_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='contact',
            field=models.CharField(default='Contact', max_length=100),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='copyright_text',
            field=models.CharField(default='© 2025 LingoSeed Global English Academy.', max_length=255),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='course_list',
            field=models.TextField(default=1, help_text='Add courses separated by commas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='courses',
            field=models.CharField(default='Courses', max_length=100),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='home',
            field=models.CharField(default='Home', max_length=100),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='instagram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer_logo/'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='tagline',
            field=models.CharField(max_length=200),
        ),
    ]
