# Generated by Django 5.2.7 on 2025-10-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_remove_footerinfo_courses_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Explore Courses', max_length=50)),
                ('button_link', models.CharField(default='/courses/', max_length=200)),
                ('teacher_image', models.ImageField(upload_to='about/')),
                ('bg_color', models.CharField(default='#F6EFCE', max_length=20)),
                ('text_color', models.CharField(default='#000', max_length=20)),
            ],
        ),
    ]
