# Generated by Django 5.2.7 on 2025-10-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0016_ourstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_description', models.TextField()),
                ('vision_title', models.CharField(default='Vision & Values', max_length=200)),
                ('vision_text', models.TextField()),
                ('approach_text', models.TextField()),
                ('values_text', models.TextField()),
                ('icon1', models.ImageField(blank=True, null=True, upload_to='story_icons/')),
                ('icon2', models.ImageField(blank=True, null=True, upload_to='story_icons/')),
                ('icon3', models.ImageField(blank=True, null=True, upload_to='story_icons/')),
            ],
        ),
    ]
