# Generated by Django 5.2.7 on 2025-10-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0018_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Explore Courses', max_length=100)),
                ('button_link', models.URLField(default='#')),
            ],
            options={
                'verbose_name': 'Our Approach',
                'verbose_name_plural': 'Our Approach Content',
            },
        ),
    ]
