# Generated by Django 5.2.7 on 2025-10-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0019_approach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approach',
            name='button_link',
        ),
    ]
