# Generated by Django 5.2.7 on 2025-10-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0021_contactdetail_footer_footercourse_quicklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
