# Generated by Django 5.2.7 on 2025-10-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0022_footer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicklink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quicklink',
            name='url',
        ),
        migrations.AddField(
            model_name='quicklink',
            name='about',
            field=models.CharField(default='About', max_length=100),
        ),
        migrations.AddField(
            model_name='quicklink',
            name='contact',
            field=models.CharField(default='Contact', max_length=100),
        ),
        migrations.AddField(
            model_name='quicklink',
            name='courses',
            field=models.CharField(default='Courses', max_length=100),
        ),
        migrations.AddField(
            model_name='quicklink',
            name='home',
            field=models.CharField(default='Home', max_length=100),
        ),
    ]
