# Generated by Django 5.2.7 on 2025-10-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0023_remove_quicklink_name_remove_quicklink_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footercourse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='footercourse',
            name='url',
        ),
        migrations.AddField(
            model_name='footercourse',
            name='course_list',
            field=models.TextField(default=1, help_text='Add courses separated by commas'),
            preserve_default=False,
        ),
    ]
