# Generated by Django 5.2.7 on 2025-10-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0025_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
