# Generated by Django 5.2.7 on 2025-11-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0026_remove_course_duration_remove_course_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='short_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('kids', 'Kids'), ('adults', 'Adults'), ('teachers', 'Teachers')], default='kids', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='courses/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
