# Generated by Django 5.2.7 on 2025-11-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0028_rename_description_course_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='short_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('kids', 'Kids'), ('adults', 'Adults'), ('teachers', 'Teachers')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='courses/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
