# Generated by Django 5.2.7 on 2025-11-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0029_rename_short_description_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
