# Generated by Django 5.2.7 on 2025-11-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0030_rename_description_course_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['category', 'id']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('kids', 'Kids'), ('adults', 'Adults'), ('teachers', 'Teachers')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='courses/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
