# Generated by Django 5.2.7 on 2025-11-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0031_alter_course_options_remove_course_short_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
