# Generated by Django 5.2.7 on 2025-11-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0032_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=150)),
                ('short_description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='courses/')),
            ],
        ),
    ]
