# Generated by Django 5.2.7 on 2025-11-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0034_kidscourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidscourse',
            name='image',
            field=models.ImageField(upload_to='courses/'),
        ),
    ]
