# Generated by Django 5.2.7 on 2025-11-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0035_alter_kidscourse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(max_length=500),
        ),
    ]
