# Generated by Django 5.2.7 on 2025-11-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0036_alter_course_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KidsCourse',
        ),
    ]
