# Generated by Django 5.2.7 on 2025-11-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0037_delete_kidscourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=500)),
                ('duration', models.CharField(max_length=150)),
                ('outcomes', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='teacher_training/')),
            ],
        ),
    ]
