# Generated by Django 5.2.7 on 2025-11-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0038_teachertraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='courses/')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='teachertraining',
            name='short_description',
        ),
        migrations.AddField(
            model_name='teachertraining',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachertraining',
            name='register_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachertraining',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachertraining',
            name='image',
            field=models.ImageField(upload_to='teacher/'),
        ),
        migrations.AlterField(
            model_name='teachertraining',
            name='outcomes',
            field=models.TextField(),
        ),
    ]
