# Generated by Django 5.2.7 on 2025-11-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0039_kidscourse_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('level', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='course_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='KidsCourse',
        ),
        migrations.DeleteModel(
            name='TeacherTraining',
        ),
    ]
