# Generated by Django 5.2.7 on 2025-11-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0042_course_level_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('outcomes', models.TextField()),
                ('fee', models.CharField(blank=True, max_length=100, null=True)),
                ('register_link', models.URLField()),
                ('image', models.ImageField(upload_to='courses/teachers/')),
            ],
        ),
    ]
