# Generated by Django 5.2.7 on 2025-11-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0043_teachertrainingcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertrainingcourse',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='teachertrainingcourse',
            name='register_link',
        ),
    ]
