# Generated by Django 5.2.7 on 2025-11-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0044_remove_teachertrainingcourse_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=200)),
                ('fee', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='adults/')),
            ],
        ),
    ]
