# Generated by Django 5.2.7 on 2025-11-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0045_adultcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultcourse',
            name='fee',
        ),
    ]
