# Generated by Django 5.2.7 on 2025-11-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0046_remove_adultcourse_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
