# Generated by Django 5.2.7 on 2025-11-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0048_contactformsubmission_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('qr_image', models.ImageField(upload_to='qr/')),
            ],
        ),
    ]
