# Generated by Django 5.2.7 on 2025-11-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0049_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
