# Generated by Django 5.2.7 on 2025-11-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0050_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
