# Generated by Django 5.2.7 on 2025-11-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0052_contactpage_email_contactpage_logo_contactpage_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='whatsapp_text',
        ),
    ]
