# Generated by Django 5.2.7 on 2025-11-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0053_remove_contactpage_email_remove_contactpage_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='whatsapp_text',
            field=models.CharField(default='MESSAGE US ON WHATSAPP', max_length=200),
        ),
    ]
