# Generated by Django 5.2.7 on 2025-11-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0054_contactpage_email_contactpage_logo_contactpage_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp_qr', models.ImageField(blank=True, null=True, upload_to='qr/')),
            ],
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='whatsapp_text',
        ),
    ]
