# Generated by Django 5.2.7 on 2025-11-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0055_contact_remove_contactpage_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='instagram',
        ),
    ]
