# Generated by Django 5.2.7 on 2025-11-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0056_remove_contact_instagram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorySection',
        ),
        migrations.AddField(
            model_name='ourstory',
            name='approach_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='icon1',
            field=models.ImageField(blank=True, null=True, upload_to='about/icons/'),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='icon2',
            field=models.ImageField(blank=True, null=True, upload_to='about/icons/'),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='icon3',
            field=models.ImageField(blank=True, null=True, upload_to='about/icons/'),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='mission_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='mission_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='values_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='vision_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='vision_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
