# Generated by Django 5.2.7 on 2025-11-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0057_delete_storysection_ourstory_approach_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_description', models.TextField()),
                ('vision_title', models.CharField(default='Vision & Values', max_length=200)),
                ('vision_text', models.TextField()),
                ('approach_text', models.TextField()),
                ('values_text', models.TextField()),
                ('icon1', models.ImageField(blank=True, null=True, upload_to='story_icons/')),
                ('icon2', models.ImageField(blank=True, null=True, upload_to='story_icons/')),
                ('icon3', models.ImageField(blank=True, null=True, upload_to='story_icons/')),
            ],
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='approach_text',
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='icon1',
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='icon2',
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='icon3',
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='mission_description',
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='mission_title',
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='values_text',
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='vision_text',
        ),
        migrations.RemoveField(
            model_name='ourstory',
            name='vision_title',
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='our_story/'),
        ),
    ]
