# Generated by Django 5.2.7 on 2025-11-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0059_courseregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregistration',
            old_name='register_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='mode',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
