# Generated by Django 5.2.7 on 2025-11-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0061_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultcourse',
            name='price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
