# Generated by Django 5.2.7 on 2025-11-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0062_adultcourse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='whatsapp_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='course_details/')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.TextField()),
                ('image', models.ImageField(upload_to='course_overview/')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
            ],
        ),
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='key_features/icons/')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='key_features/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='learning_points/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.course')),
            ],
        ),
    ]
