# Generated by Django 5.2.7 on 2025-11-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0063_alter_contact_whatsapp_qr_coursedetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoverview',
            name='course',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='course',
        ),
        migrations.RemoveField(
            model_name='keyfeature',
            name='course',
        ),
        migrations.RemoveField(
            model_name='learningpoint',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
        migrations.DeleteModel(
            name='CourseOverview',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='KeyFeature',
        ),
        migrations.DeleteModel(
            name='LearningPoint',
        ),
    ]
